### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by sajidurehman** [liujiacode/EffectiveMass#2]
Hi dear liujia
               i am trying to use your code by using following command but i am facing following error
**Command**:
python3 EffectiveMass.py -p "/home/sajid/Desktop/NbFeSb CASTEP GeomOpt" -c "NbFeSb Band Structure.xcd"

**Error:**
Traceback (most recent call last):
  File "EffectiveMass.py", line 700, in <module>
    c_paras, k_paras, b_paras = em.load(xsd_file=model_xsd_file, bs_xcd_file=bandstr_xcd_file)
  File "EffectiveMass.py", line 374, in load
    num_labels = int(cart_2d_plot[0].xpath("./cartesian_axes_2d/axis_tick_labels/@numlabels")[0])
IndexError: list index out of range

could you please guide me how to fix this error. Looking forward to hear you

**Comment by liujiacode** [comment]
Hi sajidurehman,
&nbsp;&nbsp;&nbsp;&nbsp; This error is raised because your band structure xcd file doesn't contain codes like `<AXIS_TICK_LABELS Axis="X" NumLabels="8">`, which indicate the number of high symmetry point labels in the band structure. You could open the xcd file by notepad or vscode directly and check if it is complete. Sometimes Materials Studio would keep the xcd file empty if you don't click the "Save" button or press "Ctrl + S".
&nbsp;&nbsp;&nbsp;&nbsp; Hope this will help you.
